### ISSUE TITLE
Multiple subscribers results in 'hLookAhead: end of file'

### ISSUE THREAD

**Issue by juselius** [k00mi/mqtt-hs#11]
Running multiple copies of the subscriber example results in the following error:
```
Subscriber-exe: <socket: 12>: hLookAhead: end of file
```
The code is built using ``stack lts-10.0``.

I'm running the example subscriber against Mosquitto 1.4.12.

**Comment by ibnuda** [comment]
Got the same result. But in my case, I use this library as a subscriber client and publisher. When I publish message and then disconnect it, the subcriber also disconnect.
I fixed this problem with the following snippet:
```
runSubscribtion = keepRunningBuddy subscribeSensor
  where
    keepRunningBuddy process = do
      x <- tryJust (guard . isEOFError) process
      case x of
        Left e -> do
          threadDealy $ 10 * 100 * 1000
          _ <- forkIO process
          keepRunningBuddy process
        Right r -> return ()
```

**Comment by juselius** [comment]
@ibnuda which broker are you using? I'm wondering if this is a mosquitto related problem, or if it's more general.

**Comment by ibnuda** [comment]
Mosquitto. Standard Debian 9 (iirc) installation.

**Comment by k00mi** [comment]
@juselius: Are you running multiple instances of the same binary at the same time? Then both will connect using the same username and mosquitto will drop one connection.

@ibnuda: I'm not sure I understand what you're doing, more of your code (in particular the parts where you connect and disconnect) would be helpful. If you are using one connection (i.e. call `Network.MQTT.run` once) for both publishing and subscribing, then terminating (`Network.MQTT.disconnect`ing) that connection will also drop the subscriptions because their underlying connection is gone, as that is exactly what disconnect is supposed to do. I'm not sure what you are trying to achieve by calling `disconnect` after publishing, there is no need for that if you want to keep using the same connection for subscriptions.

**Comment by ibnuda** [comment]
There are two instances of client in my code.
- Long running subscriptions. Which subscribes a lot of things.
- Once-off publish client for once a while. 
Reason to do that:
Because the publisher rarely be used, it should be a short lived instance. Not only that, there are many topics that should be sent that couldn't be decided programmatically.

Expected:
```
|
|                      o
|                      |
|                      |
|                      |
|                      o
|                    publish
subscribe 
```
The subscribe client should keep running while once-in-a-while publish client finishing its job.

Actual:
```
|
|                      o
|                      |
|                      |
|                      |
o                      o
subscribe        publish 
```
The subscribe client disconnected when once-in-a-while publish client finished its job (and disconnected).

**Comment by k00mi** [comment]
@ibnuda: Are you using the same username / client ID for both connections? Then mosquitto will drop the connection for subscriptions when the one for publishing is established. You could also stick to one connection for both subscriptions and publishing, I don't think there is any advantage to opening new connections for publishing.

**Comment by juselius** [comment]
@k00mi You probably mean clientid, not username. I changed the default cClientID, and now it works perfectly:

```hs
cid <- randomRIO (0, 999999 :: Int)
( MQTT.defaultConfig cmds pubChan )
{ MQTT.cClientID = T.pack $ "test-" ++ show cid
}
```

Thank you for your help!
